.Dd 1/20/10
.Dt detectdisplays 1
.Os Darwin
.Sh NAME
.Nm detectdisplays
.Nd Detect attached displays.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
Call
.Nm
to detect all attached displays.
.Nm
supports up to 16 displays. There are no command-line options.
.Sh FILES
.Bl -tag -width "/usr/local/share/man/man1/detectdisplays.1" -compact
.It Pa /usr/local/bin/detectdisplays
The
.Nm
binary.
.It Pa /usr/local/share/man/man1/detectdisplays.1
This man page.
.El